import { supabase } from '@/src/lib/supabase';

export interface UserTrustStatus {
  id: string;
  user_id: string;
  successful_purchases: number;
  successful_sales: number;
  total_transactions: number;
  is_trusted: boolean;
  trust_earned_at: string | null;
  created_at: string;
  updated_at: string;
}

export class TrustService {
  /**
   * Get user's trust status from database
   */
  static async getUserTrustStatus(
    userId: string
  ): Promise<{ success: boolean; data?: UserTrustStatus; error?: string }> {
    try {
      if (!userId || userId.trim() === '') {
        return { success: false, error: 'User ID is required' };
      }

      const { data, error } = await supabase
        .from('user_trust_status')
        .select('*')
        .eq('user_id', userId)
        .single();

      if (error) {
        if (error.code === 'PGRST116') {
          // No trust status record exists yet - user is not trusted
          return {
            success: true,
            data: {
              id: '', // Will be generated by database
              user_id: userId,
              successful_purchases: 0,
              successful_sales: 0,
              total_transactions: 0,
              is_trusted: false,
              trust_earned_at: null,
              created_at: new Date().toISOString(),
              updated_at: new Date().toISOString(),
            }
          };
        }
        console.error('Error fetching user trust status:', error);
        return { success: false, error: error.message };
      }

      return { success: true, data };
    } catch (error) {
      console.error('Unexpected error fetching user trust status:', error);
      return { success: false, error: 'Failed to fetch trust status' };
    }
  }

  /**
   * Check if user is trusted (convenience method)
   */
  static async isUserTrusted(userId: string): Promise<boolean> {
    try {
      if (!userId || userId.trim() === '') {
        return false;
      }

      const result = await this.getUserTrustStatus(userId);
      return result.success && result.data?.is_trusted === true;
    } catch (error) {
      console.error('Error checking if user is trusted:', error);
      return false;
    }
  }

  /**
   * Get trust status for multiple users
   */
  static async getUsersTrustStatus(
    userIds: string[]
  ): Promise<{ success: boolean; data?: UserTrustStatus[]; error?: string }> {
    try {
      if (!userIds || userIds.length === 0) {
        return { success: true, data: [] };
      }

      // Filter out invalid user IDs
      const validUserIds = userIds.filter(id => id && id.trim() !== '');
      if (validUserIds.length === 0) {
        return { success: true, data: [] };
      }

      const { data, error } = await supabase
        .from('user_trust_status')
        .select('*')
        .in('user_id', validUserIds);

      if (error) {
        console.error('Error fetching users trust status:', error);
        return { success: false, error: error.message };
      }

      return { success: true, data: data || [] };
    } catch (error) {
      console.error('Unexpected error fetching users trust status:', error);
      return { success: false, error: 'Failed to fetch trust status' };
    }
  }

  /**
   * Get user's rating statistics (with penalty adjustments applied)
   */
  static async getUserRatingStats(
    userId: string
  ): Promise<{
    success: boolean;
    data?: {
      totalRatings: number;
      averageRating: number;
      baseRating: number;
      ratingAdjustment: number;
      ratingBreakdown: { [key: number]: number };
    };
    error?: string;
  }> {
    try {
      if (!userId || userId.trim() === '') {
        return { success: false, error: 'User ID is required' };
      }

      // Fetch ratings and profile adjustment in parallel
      const [ratingsResult, profileResult] = await Promise.all([
        supabase
          .from('user_ratings')
          .select('rating')
          .eq('rated_user_id', userId),
        supabase
          .from('profiles')
          .select('seller_rating_adjustment')
          .eq('id', userId)
          .single(),
      ]);

      if (ratingsResult.error) {
        console.error('Error fetching user rating stats:', ratingsResult.error);
        return { success: false, error: ratingsResult.error.message };
      }

      const ratings = ratingsResult.data || [];
      const totalRatings = ratings.length;
      const baseRating = totalRatings > 0
        ? ratings.reduce((sum, r) => sum + r.rating, 0) / totalRatings
        : 0;

      // Get rating adjustment from profile (penalties reduce rating)
      const ratingAdjustment = profileResult.data?.seller_rating_adjustment || 0;

      // Apply adjustment and clamp between 0-5
      const adjustedRating = Math.max(0, Math.min(5, baseRating + ratingAdjustment));

      // Create rating breakdown (1-5 stars)
      const ratingBreakdown: { [key: number]: number } = { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0 };
      ratings.forEach(r => {
        if (r.rating >= 1 && r.rating <= 5) {
          ratingBreakdown[Math.round(r.rating)]++;
        }
      });

      return {
        success: true,
        data: {
          totalRatings,
          averageRating: Math.round(adjustedRating * 10) / 10, // Adjusted rating
          baseRating: Math.round(baseRating * 10) / 10,
          ratingAdjustment,
          ratingBreakdown,
        },
      };
    } catch (error) {
      console.error('Unexpected error fetching user rating stats:', error);
      return { success: false, error: 'Failed to fetch rating statistics' };
    }
  }

  /**
   * Get user's transaction count from ticket sales
   */
  static async getUserTransactionCount(userId: string): Promise<number> {
    try {
      if (!userId || userId.trim() === '') {
        return 0;
      }

      const { data, error } = await supabase
        .from('ticket_sales')
        .select('id')
        .or(`seller_id.eq.${userId},buyer_id.eq.${userId}`);

      if (error) {
        console.error('Error fetching user transaction count:', error);
        return 0;
      }

      return data?.length || 0;
    } catch (error) {
      console.error('Unexpected error fetching transaction count:', error);
      return 0;
    }
  }
}